// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// BranchRepository is an autogenerated mock type for the BranchRepository type
type BranchRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: branch
func (_m *BranchRepository) Create(branch *domain.Branch) error {
	ret := _m.Called(branch)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Branch) error); ok {
		r0 = rf(branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateStockTransfer provides a mock function with given fields: transfer
func (_m *BranchRepository) CreateStockTransfer(transfer *domain.StockTransfer) error {
	ret := _m.Called(transfer)

	if len(ret) == 0 {
		panic("no return value specified for CreateStockTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.StockTransfer) error); ok {
		r0 = rf(transfer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *BranchRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *BranchRepository) GetAll() ([]domain.Branch, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Branch, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Branch); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *BranchRepository) GetByID(id string) (*domain.Branch, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Branch, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Branch); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockTransferByID provides a mock function with given fields: id
func (_m *BranchRepository) GetStockTransferByID(id string) (*domain.StockTransfer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetStockTransferByID")
	}

	var r0 *domain.StockTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.StockTransfer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.StockTransfer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StockTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStockTransfers provides a mock function with given fields: page, limit, status
func (_m *BranchRepository) GetStockTransfers(page int, limit int, status string) ([]domain.StockTransfer, int64, error) {
	ret := _m.Called(page, limit, status)

	if len(ret) == 0 {
		panic("no return value specified for GetStockTransfers")
	}

	var r0 []domain.StockTransfer
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.StockTransfer, int64, error)); ok {
		return rf(page, limit, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.StockTransfer); ok {
		r0 = rf(page, limit, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StockTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: branch
func (_m *BranchRepository) Update(branch *domain.Branch) error {
	ret := _m.Called(branch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Branch) error); ok {
		r0 = rf(branch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStockTransferStatus provides a mock function with given fields: id, status
func (_m *BranchRepository) UpdateStockTransferStatus(id string, status string) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStockTransferStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBranchRepository creates a new instance of BranchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBranchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BranchRepository {
	mock := &BranchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
