// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// BudgetRepository is an autogenerated mock type for the BudgetRepository type
type BudgetRepository struct {
	mock.Mock
}

// CreateApprovalWorkflow provides a mock function with given fields: wf
func (_m *BudgetRepository) CreateApprovalWorkflow(wf *domain.ApprovalWorkflow) error {
	ret := _m.Called(wf)

	if len(ret) == 0 {
		panic("no return value specified for CreateApprovalWorkflow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ApprovalWorkflow) error); ok {
		r0 = rf(wf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBudget provides a mock function with given fields: budget
func (_m *BudgetRepository) CreateBudget(budget *domain.Budget) error {
	ret := _m.Called(budget)

	if len(ret) == 0 {
		panic("no return value specified for CreateBudget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Budget) error); ok {
		r0 = rf(budget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateExpenseApproval provides a mock function with given fields: approval
func (_m *BudgetRepository) CreateExpenseApproval(approval *domain.ExpenseApproval) error {
	ret := _m.Called(approval)

	if len(ret) == 0 {
		panic("no return value specified for CreateExpenseApproval")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ExpenseApproval) error); ok {
		r0 = rf(approval)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteApprovalWorkflow provides a mock function with given fields: id
func (_m *BudgetRepository) DeleteApprovalWorkflow(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApprovalWorkflow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBudget provides a mock function with given fields: id
func (_m *BudgetRepository) DeleteBudget(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBudget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetApprovalWorkflows provides a mock function with no fields
func (_m *BudgetRepository) GetApprovalWorkflows() ([]domain.ApprovalWorkflow, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetApprovalWorkflows")
	}

	var r0 []domain.ApprovalWorkflow
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ApprovalWorkflow, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ApprovalWorkflow); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ApprovalWorkflow)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBudgetByID provides a mock function with given fields: id
func (_m *BudgetRepository) GetBudgetByID(id string) (*domain.Budget, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBudgetByID")
	}

	var r0 *domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Budget, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Budget); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Budget)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBudgets provides a mock function with no fields
func (_m *BudgetRepository) GetBudgets() ([]domain.Budget, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBudgets")
	}

	var r0 []domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Budget, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Budget); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Budget)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpenseApprovals provides a mock function with given fields: expenseID
func (_m *BudgetRepository) GetExpenseApprovals(expenseID string) ([]domain.ExpenseApproval, error) {
	ret := _m.Called(expenseID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseApprovals")
	}

	var r0 []domain.ExpenseApproval
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.ExpenseApproval, error)); ok {
		return rf(expenseID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.ExpenseApproval); ok {
		r0 = rf(expenseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ExpenseApproval)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(expenseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSpentForBudget provides a mock function with given fields: budgetID
func (_m *BudgetRepository) GetSpentForBudget(budgetID string) (float64, error) {
	ret := _m.Called(budgetID)

	if len(ret) == 0 {
		panic("no return value specified for GetSpentForBudget")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(budgetID)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(budgetID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(budgetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateApprovalWorkflow provides a mock function with given fields: wf
func (_m *BudgetRepository) UpdateApprovalWorkflow(wf *domain.ApprovalWorkflow) error {
	ret := _m.Called(wf)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApprovalWorkflow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ApprovalWorkflow) error); ok {
		r0 = rf(wf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBudget provides a mock function with given fields: budget
func (_m *BudgetRepository) UpdateBudget(budget *domain.Budget) error {
	ret := _m.Called(budget)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBudget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Budget) error); ok {
		r0 = rf(budget)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBudgetRepository creates a new instance of BudgetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBudgetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BudgetRepository {
	mock := &BudgetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
