// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CommissionRepository is an autogenerated mock type for the CommissionRepository type
type CommissionRepository struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: payment
func (_m *CommissionRepository) CreatePayment(payment *domain.CommissionPayment) error {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CommissionPayment) error); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRule provides a mock function with given fields: rule
func (_m *CommissionRepository) CreateRule(rule *domain.CommissionRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CommissionRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRule provides a mock function with given fields: id
func (_m *CommissionRepository) DeleteRule(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentsByPeriod provides a mock function with given fields: periodStart, periodEnd
func (_m *CommissionRepository) GetPaymentsByPeriod(periodStart string, periodEnd string) ([]domain.CommissionPayment, error) {
	ret := _m.Called(periodStart, periodEnd)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentsByPeriod")
	}

	var r0 []domain.CommissionPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]domain.CommissionPayment, error)); ok {
		return rf(periodStart, periodEnd)
	}
	if rf, ok := ret.Get(0).(func(string, string) []domain.CommissionPayment); ok {
		r0 = rf(periodStart, periodEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CommissionPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(periodStart, periodEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentsByStaff provides a mock function with given fields: staffID
func (_m *CommissionRepository) GetPaymentsByStaff(staffID string) ([]domain.CommissionPayment, error) {
	ret := _m.Called(staffID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentsByStaff")
	}

	var r0 []domain.CommissionPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.CommissionPayment, error)); ok {
		return rf(staffID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.CommissionPayment); ok {
		r0 = rf(staffID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CommissionPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(staffID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRuleByID provides a mock function with given fields: id
func (_m *CommissionRepository) GetRuleByID(id string) (*domain.CommissionRule, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRuleByID")
	}

	var r0 *domain.CommissionRule
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.CommissionRule, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.CommissionRule); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommissionRule)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRules provides a mock function with no fields
func (_m *CommissionRepository) GetRules() ([]domain.CommissionRule, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRules")
	}

	var r0 []domain.CommissionRule
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.CommissionRule, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.CommissionRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CommissionRule)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePaymentStatus provides a mock function with given fields: id, status
func (_m *CommissionRepository) UpdatePaymentStatus(id uint, status string) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRule provides a mock function with given fields: rule
func (_m *CommissionRepository) UpdateRule(rule *domain.CommissionRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CommissionRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommissionRepository creates a new instance of CommissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommissionRepository {
	mock := &CommissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
