// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyRepository is an autogenerated mock type for the CurrencyRepository type
type CurrencyRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: currency
func (_m *CurrencyRepository) Create(currency *domain.Currency) error {
	ret := _m.Called(currency)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Currency) error); ok {
		r0 = rf(currency)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTransaction provides a mock function with given fields: tx
func (_m *CurrencyRepository) CreateTransaction(tx *domain.CurrencyTransaction) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CurrencyTransaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CurrencyRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *CurrencyRepository) GetAll() ([]domain.Currency, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Currency, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Currency); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBaseCurrency provides a mock function with no fields
func (_m *CurrencyRepository) GetBaseCurrency() (*domain.Currency, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBaseCurrency")
	}

	var r0 *domain.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.Currency, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.Currency); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCode provides a mock function with given fields: code
func (_m *CurrencyRepository) GetByCode(code string) (*domain.Currency, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *domain.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Currency, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Currency); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *CurrencyRepository) GetByID(id string) (*domain.Currency, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Currency, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Currency); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactions provides a mock function with given fields: saleID
func (_m *CurrencyRepository) GetTransactions(saleID string) ([]domain.CurrencyTransaction, error) {
	ret := _m.Called(saleID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []domain.CurrencyTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.CurrencyTransaction, error)); ok {
		return rf(saleID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.CurrencyTransaction); ok {
		r0 = rf(saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CurrencyTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: currency
func (_m *CurrencyRepository) Update(currency *domain.Currency) error {
	ret := _m.Called(currency)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Currency) error); ok {
		r0 = rf(currency)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCurrencyRepository creates a new instance of CurrencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyRepository {
	mock := &CurrencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
