// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// DeliveryRepository is an autogenerated mock type for the DeliveryRepository type
type DeliveryRepository struct {
	mock.Mock
}

// CreateDriver provides a mock function with given fields: driver
func (_m *DeliveryRepository) CreateDriver(driver *domain.DeliveryDriver) error {
	ret := _m.Called(driver)

	if len(ret) == 0 {
		panic("no return value specified for CreateDriver")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.DeliveryDriver) error); ok {
		r0 = rf(driver)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrder provides a mock function with given fields: order
func (_m *DeliveryRepository) CreateOrder(order *domain.DeliveryOrder) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.DeliveryOrder) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDriver provides a mock function with given fields: id
func (_m *DeliveryRepository) DeleteDriver(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDriver")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDriverByID provides a mock function with given fields: id
func (_m *DeliveryRepository) GetDriverByID(id string) (*domain.DeliveryDriver, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDriverByID")
	}

	var r0 *domain.DeliveryDriver
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.DeliveryDriver, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.DeliveryDriver); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DeliveryDriver)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDrivers provides a mock function with no fields
func (_m *DeliveryRepository) GetDrivers() ([]domain.DeliveryDriver, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDrivers")
	}

	var r0 []domain.DeliveryDriver
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.DeliveryDriver, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.DeliveryDriver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeliveryDriver)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: id
func (_m *DeliveryRepository) GetOrderByID(id string) (*domain.DeliveryOrder, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *domain.DeliveryOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.DeliveryOrder, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.DeliveryOrder); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DeliveryOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderBySaleID provides a mock function with given fields: saleID
func (_m *DeliveryRepository) GetOrderBySaleID(saleID string) (*domain.DeliveryOrder, error) {
	ret := _m.Called(saleID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderBySaleID")
	}

	var r0 *domain.DeliveryOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.DeliveryOrder, error)); ok {
		return rf(saleID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.DeliveryOrder); ok {
		r0 = rf(saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DeliveryOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrders provides a mock function with given fields: page, limit, status
func (_m *DeliveryRepository) GetOrders(page int, limit int, status string) ([]domain.DeliveryOrder, int64, error) {
	ret := _m.Called(page, limit, status)

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []domain.DeliveryOrder
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.DeliveryOrder, int64, error)); ok {
		return rf(page, limit, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.DeliveryOrder); ok {
		r0 = rf(page, limit, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeliveryOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateDriver provides a mock function with given fields: driver
func (_m *DeliveryRepository) UpdateDriver(driver *domain.DeliveryDriver) error {
	ret := _m.Called(driver)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDriver")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.DeliveryDriver) error); ok {
		r0 = rf(driver)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrder provides a mock function with given fields: order
func (_m *DeliveryRepository) UpdateOrder(order *domain.DeliveryOrder) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.DeliveryOrder) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeliveryRepository creates a new instance of DeliveryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeliveryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeliveryRepository {
	mock := &DeliveryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
