// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// FinanceRepository is an autogenerated mock type for the FinanceRepository type
type FinanceRepository struct {
	mock.Mock
}

// CreateDiscount provides a mock function with given fields: discount
func (_m *FinanceRepository) CreateDiscount(discount *domain.Discount) error {
	ret := _m.Called(discount)

	if len(ret) == 0 {
		panic("no return value specified for CreateDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Discount) error); ok {
		r0 = rf(discount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateExpense provides a mock function with given fields: expense
func (_m *FinanceRepository) CreateExpense(expense *domain.Expense) error {
	ret := _m.Called(expense)

	if len(ret) == 0 {
		panic("no return value specified for CreateExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Expense) error); ok {
		r0 = rf(expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePayment provides a mock function with given fields: payment
func (_m *FinanceRepository) CreatePayment(payment *domain.Payment) error {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Payment) error); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDiscount provides a mock function with given fields: id
func (_m *FinanceRepository) DeleteDiscount(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExpense provides a mock function with given fields: id
func (_m *FinanceRepository) DeleteExpense(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDiscounts provides a mock function with no fields
func (_m *FinanceRepository) GetDiscounts() ([]domain.Discount, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDiscounts")
	}

	var r0 []domain.Discount
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Discount, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Discount); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Discount)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpenseCategories provides a mock function with no fields
func (_m *FinanceRepository) GetExpenseCategories() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseCategories")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpenses provides a mock function with given fields: page, limit, category
func (_m *FinanceRepository) GetExpenses(page int, limit int, category string) ([]domain.Expense, int64, error) {
	ret := _m.Called(page, limit, category)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenses")
	}

	var r0 []domain.Expense
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.Expense, int64, error)); ok {
		return rf(page, limit, category)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.Expense); ok {
		r0 = rf(page, limit, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Expense)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, category)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, category)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPayments provides a mock function with given fields: saleID
func (_m *FinanceRepository) GetPayments(saleID string) ([]domain.Payment, error) {
	ret := _m.Called(saleID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayments")
	}

	var r0 []domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Payment, error)); ok {
		return rf(saleID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Payment); ok {
		r0 = rf(saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentsByCustomerID provides a mock function with given fields: customerID
func (_m *FinanceRepository) GetPaymentsByCustomerID(customerID string) ([]domain.Payment, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentsByCustomerID")
	}

	var r0 []domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Payment, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Payment); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDiscount provides a mock function with given fields: discount
func (_m *FinanceRepository) UpdateDiscount(discount *domain.Discount) error {
	ret := _m.Called(discount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Discount) error); ok {
		r0 = rf(discount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateExpense provides a mock function with given fields: expense
func (_m *FinanceRepository) UpdateExpense(expense *domain.Expense) error {
	ret := _m.Called(expense)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Expense) error); ok {
		r0 = rf(expense)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFinanceRepository creates a new instance of FinanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinanceRepository {
	mock := &FinanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
