// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// GiftCardRepository is an autogenerated mock type for the GiftCardRepository type
type GiftCardRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: card
func (_m *GiftCardRepository) Create(card *domain.GiftCard) error {
	ret := _m.Called(card)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.GiftCard) error); ok {
		r0 = rf(card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTransaction provides a mock function with given fields: tx
func (_m *GiftCardRepository) CreateTransaction(tx *domain.GiftCardTransaction) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.GiftCardTransaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateVoucher provides a mock function with given fields: v
func (_m *GiftCardRepository) CreateVoucher(v *domain.Voucher) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for CreateVoucher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Voucher) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *GiftCardRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteVoucher provides a mock function with given fields: id
func (_m *GiftCardRepository) DeleteVoucher(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVoucher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit
func (_m *GiftCardRepository) GetAll(page int, limit int) ([]domain.GiftCard, int64, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.GiftCard
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.GiftCard, int64, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.GiftCard); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByCode provides a mock function with given fields: code
func (_m *GiftCardRepository) GetByCode(code string) (*domain.GiftCard, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *domain.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.GiftCard, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.GiftCard); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *GiftCardRepository) GetByID(id string) (*domain.GiftCard, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.GiftCard
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.GiftCard, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.GiftCard); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GiftCard)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactions provides a mock function with given fields: cardID
func (_m *GiftCardRepository) GetTransactions(cardID string) ([]domain.GiftCardTransaction, error) {
	ret := _m.Called(cardID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []domain.GiftCardTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.GiftCardTransaction, error)); ok {
		return rf(cardID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.GiftCardTransaction); ok {
		r0 = rf(cardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GiftCardTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoucherByCode provides a mock function with given fields: code
func (_m *GiftCardRepository) GetVoucherByCode(code string) (*domain.Voucher, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetVoucherByCode")
	}

	var r0 *domain.Voucher
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Voucher, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Voucher); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Voucher)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVouchers provides a mock function with no fields
func (_m *GiftCardRepository) GetVouchers() ([]domain.Voucher, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVouchers")
	}

	var r0 []domain.Voucher
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Voucher, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Voucher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Voucher)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementVoucherUsage provides a mock function with given fields: id
func (_m *GiftCardRepository) IncrementVoucherUsage(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementVoucherUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: card
func (_m *GiftCardRepository) Update(card *domain.GiftCard) error {
	ret := _m.Called(card)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.GiftCard) error); ok {
		r0 = rf(card)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVoucher provides a mock function with given fields: v
func (_m *GiftCardRepository) UpdateVoucher(v *domain.Voucher) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVoucher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Voucher) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGiftCardRepository creates a new instance of GiftCardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGiftCardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GiftCardRepository {
	mock := &GiftCardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
