// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// KioskRepository is an autogenerated mock type for the KioskRepository type
type KioskRepository struct {
	mock.Mock
}

// CreateLayout provides a mock function with given fields: layout
func (_m *KioskRepository) CreateLayout(layout *domain.KioskLayout) error {
	ret := _m.Called(layout)

	if len(ret) == 0 {
		panic("no return value specified for CreateLayout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KioskLayout) error); ok {
		r0 = rf(layout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSession provides a mock function with given fields: session
func (_m *KioskRepository) CreateSession(session *domain.KioskSession) error {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KioskSession) error); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLayout provides a mock function with given fields: id
func (_m *KioskRepository) DeleteLayout(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLayout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveSessions provides a mock function with no fields
func (_m *KioskRepository) GetActiveSessions() ([]domain.KioskSession, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSessions")
	}

	var r0 []domain.KioskSession
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.KioskSession, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.KioskSession); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.KioskSession)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLayoutByID provides a mock function with given fields: id
func (_m *KioskRepository) GetLayoutByID(id string) (*domain.KioskLayout, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetLayoutByID")
	}

	var r0 *domain.KioskLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.KioskLayout, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.KioskLayout); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KioskLayout)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLayouts provides a mock function with no fields
func (_m *KioskRepository) GetLayouts() ([]domain.KioskLayout, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLayouts")
	}

	var r0 []domain.KioskLayout
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.KioskLayout, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.KioskLayout); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.KioskLayout)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLayout provides a mock function with given fields: layout
func (_m *KioskRepository) UpdateLayout(layout *domain.KioskLayout) error {
	ret := _m.Called(layout)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLayout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KioskLayout) error); ok {
		r0 = rf(layout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSession provides a mock function with given fields: session
func (_m *KioskRepository) UpdateSession(session *domain.KioskSession) error {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KioskSession) error); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKioskRepository creates a new instance of KioskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKioskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KioskRepository {
	mock := &KioskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
