// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// KitchenRepository is an autogenerated mock type for the KitchenRepository type
type KitchenRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: order
func (_m *KitchenRepository) CreateOrder(order *domain.KitchenOrder) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KitchenOrder) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateStation provides a mock function with given fields: station
func (_m *KitchenRepository) CreateStation(station *domain.KitchenStation) error {
	ret := _m.Called(station)

	if len(ret) == 0 {
		panic("no return value specified for CreateStation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KitchenStation) error); ok {
		r0 = rf(station)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteStation provides a mock function with given fields: id
func (_m *KitchenRepository) DeleteStation(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderByID provides a mock function with given fields: id
func (_m *KitchenRepository) GetOrderByID(id string) (*domain.KitchenOrder, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *domain.KitchenOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.KitchenOrder, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.KitchenOrder); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KitchenOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderBySaleID provides a mock function with given fields: saleID
func (_m *KitchenRepository) GetOrderBySaleID(saleID string) (*domain.KitchenOrder, error) {
	ret := _m.Called(saleID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderBySaleID")
	}

	var r0 *domain.KitchenOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.KitchenOrder, error)); ok {
		return rf(saleID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.KitchenOrder); ok {
		r0 = rf(saleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KitchenOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(saleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingOrders provides a mock function with no fields
func (_m *KitchenRepository) GetPendingOrders() ([]domain.KitchenOrder, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOrders")
	}

	var r0 []domain.KitchenOrder
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.KitchenOrder, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.KitchenOrder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.KitchenOrder)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStations provides a mock function with no fields
func (_m *KitchenRepository) GetStations() ([]domain.KitchenStation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStations")
	}

	var r0 []domain.KitchenStation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.KitchenStation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.KitchenStation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.KitchenStation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: order
func (_m *KitchenRepository) UpdateOrder(order *domain.KitchenOrder) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KitchenOrder) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrderItemStatus provides a mock function with given fields: orderID, itemID, status
func (_m *KitchenRepository) UpdateOrderItemStatus(orderID string, itemID uint, status string) error {
	ret := _m.Called(orderID, itemID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderItemStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uint, string) error); ok {
		r0 = rf(orderID, itemID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStation provides a mock function with given fields: station
func (_m *KitchenRepository) UpdateStation(station *domain.KitchenStation) error {
	ret := _m.Called(station)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.KitchenStation) error); ok {
		r0 = rf(station)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKitchenRepository creates a new instance of KitchenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKitchenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KitchenRepository {
	mock := &KitchenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
