// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// KitRepository is an autogenerated mock type for the KitRepository type
type KitRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: kit
func (_m *KitRepository) Create(kit *domain.ProductKit) error {
	ret := _m.Called(kit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProductKit) error); ok {
		r0 = rf(kit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *KitRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *KitRepository) GetAll() ([]domain.ProductKit, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.ProductKit
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ProductKit, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ProductKit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductKit)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *KitRepository) GetByID(id string) (*domain.ProductKit, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.ProductKit
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.ProductKit, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.ProductKit); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductKit)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: kit
func (_m *KitRepository) Update(kit *domain.ProductKit) error {
	ret := _m.Called(kit)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProductKit) error); ok {
		r0 = rf(kit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKitRepository creates a new instance of KitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KitRepository {
	mock := &KitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
