// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// LoyaltyRepository is an autogenerated mock type for the LoyaltyRepository type
type LoyaltyRepository struct {
	mock.Mock
}

// CreateRedemption provides a mock function with given fields: redemption
func (_m *LoyaltyRepository) CreateRedemption(redemption *domain.LoyaltyRedemption) error {
	ret := _m.Called(redemption)

	if len(ret) == 0 {
		panic("no return value specified for CreateRedemption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoyaltyRedemption) error); ok {
		r0 = rf(redemption)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateRule provides a mock function with given fields: rule
func (_m *LoyaltyRepository) CreateRule(rule *domain.LoyaltyRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoyaltyRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTier provides a mock function with given fields: tier
func (_m *LoyaltyRepository) CreateTier(tier *domain.LoyaltyTier) error {
	ret := _m.Called(tier)

	if len(ret) == 0 {
		panic("no return value specified for CreateTier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoyaltyTier) error); ok {
		r0 = rf(tier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTransaction provides a mock function with given fields: tx
func (_m *LoyaltyRepository) CreateTransaction(tx *domain.LoyaltyTransaction) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoyaltyTransaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTier provides a mock function with given fields: id
func (_m *LoyaltyRepository) DeleteTier(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveRule provides a mock function with no fields
func (_m *LoyaltyRepository) GetActiveRule() (*domain.LoyaltyRule, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveRule")
	}

	var r0 *domain.LoyaltyRule
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.LoyaltyRule, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.LoyaltyRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoyaltyRule)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedemptionsByCustomer provides a mock function with given fields: customerID
func (_m *LoyaltyRepository) GetRedemptionsByCustomer(customerID string) ([]domain.LoyaltyRedemption, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetRedemptionsByCustomer")
	}

	var r0 []domain.LoyaltyRedemption
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.LoyaltyRedemption, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.LoyaltyRedemption); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LoyaltyRedemption)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRules provides a mock function with no fields
func (_m *LoyaltyRepository) GetRules() ([]domain.LoyaltyRule, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRules")
	}

	var r0 []domain.LoyaltyRule
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.LoyaltyRule, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.LoyaltyRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LoyaltyRule)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTiers provides a mock function with no fields
func (_m *LoyaltyRepository) GetTiers() ([]domain.LoyaltyTier, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTiers")
	}

	var r0 []domain.LoyaltyTier
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.LoyaltyTier, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.LoyaltyTier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LoyaltyTier)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByCustomer provides a mock function with given fields: customerID
func (_m *LoyaltyRepository) GetTransactionsByCustomer(customerID string) ([]domain.LoyaltyTransaction, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByCustomer")
	}

	var r0 []domain.LoyaltyTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.LoyaltyTransaction, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.LoyaltyTransaction); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LoyaltyTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRule provides a mock function with given fields: rule
func (_m *LoyaltyRepository) UpdateRule(rule *domain.LoyaltyRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoyaltyRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTier provides a mock function with given fields: tier
func (_m *LoyaltyRepository) UpdateTier(tier *domain.LoyaltyTier) error {
	ret := _m.Called(tier)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTier")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.LoyaltyTier) error); ok {
		r0 = rf(tier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLoyaltyRepository creates a new instance of LoyaltyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoyaltyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoyaltyRepository {
	mock := &LoyaltyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
