// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MessagingRepository is an autogenerated mock type for the MessagingRepository type
type MessagingRepository struct {
	mock.Mock
}

// CreateLog provides a mock function with given fields: log
func (_m *MessagingRepository) CreateLog(log *domain.MessageLog) error {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for CreateLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MessageLog) error); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateProvider provides a mock function with given fields: p
func (_m *MessagingRepository) CreateProvider(p *domain.MessagingProvider) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for CreateProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MessagingProvider) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTemplate provides a mock function with given fields: t
func (_m *MessagingRepository) CreateTemplate(t *domain.MessageTemplate) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MessageTemplate) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProvider provides a mock function with given fields: id
func (_m *MessagingRepository) DeleteProvider(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTemplate provides a mock function with given fields: id
func (_m *MessagingRepository) DeleteTemplate(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLogs provides a mock function with given fields: page, limit
func (_m *MessagingRepository) GetLogs(page int, limit int) ([]domain.MessageLog, int64, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []domain.MessageLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.MessageLog, int64, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.MessageLog); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetProviderByID provides a mock function with given fields: id
func (_m *MessagingRepository) GetProviderByID(id string) (*domain.MessagingProvider, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderByID")
	}

	var r0 *domain.MessagingProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.MessagingProvider, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.MessagingProvider); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MessagingProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProviders provides a mock function with no fields
func (_m *MessagingRepository) GetProviders() ([]domain.MessagingProvider, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProviders")
	}

	var r0 []domain.MessagingProvider
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.MessagingProvider, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.MessagingProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessagingProvider)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplates provides a mock function with no fields
func (_m *MessagingRepository) GetTemplates() ([]domain.MessageTemplate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTemplates")
	}

	var r0 []domain.MessageTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.MessageTemplate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.MessageTemplate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MessageTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProvider provides a mock function with given fields: p
func (_m *MessagingRepository) UpdateProvider(p *domain.MessagingProvider) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MessagingProvider) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTemplate provides a mock function with given fields: t
func (_m *MessagingRepository) UpdateTemplate(t *domain.MessageTemplate) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MessageTemplate) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessagingRepository creates a new instance of MessagingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagingRepository {
	mock := &MessagingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
