// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// CreateLog provides a mock function with given fields: log
func (_m *NotificationRepository) CreateLog(log *domain.NotificationLog) error {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for CreateLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.NotificationLog) error); ok {
		r0 = rf(log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTemplate provides a mock function with given fields: t
func (_m *NotificationRepository) CreateTemplate(t *domain.NotificationTemplate) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.NotificationTemplate) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTemplate provides a mock function with given fields: id
func (_m *NotificationRepository) DeleteTemplate(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLogs provides a mock function with given fields: page, limit
func (_m *NotificationRepository) GetLogs(page int, limit int) ([]domain.NotificationLog, int64, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []domain.NotificationLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.NotificationLog, int64, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.NotificationLog); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSettings provides a mock function with no fields
func (_m *NotificationRepository) GetSettings() (*domain.NotificationSettings, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *domain.NotificationSettings
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.NotificationSettings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.NotificationSettings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NotificationSettings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplates provides a mock function with no fields
func (_m *NotificationRepository) GetTemplates() ([]domain.NotificationTemplate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTemplates")
	}

	var r0 []domain.NotificationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.NotificationTemplate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.NotificationTemplate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.NotificationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSettings provides a mock function with given fields: s
func (_m *NotificationRepository) UpdateSettings(s *domain.NotificationSettings) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.NotificationSettings) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTemplate provides a mock function with given fields: t
func (_m *NotificationRepository) UpdateTemplate(t *domain.NotificationTemplate) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.NotificationTemplate) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
