// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: product
func (_m *ProductRepository) Create(product *domain.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCategory provides a mock function with given fields: cat
func (_m *ProductRepository) CreateCategory(cat *domain.Category) error {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(cat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *ProductRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit, search, category
func (_m *ProductRepository) GetAll(page int, limit int, search string, category string) (*domain.PaginatedProducts, error) {
	ret := _m.Called(page, limit, search, category)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *domain.PaginatedProducts
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) (*domain.PaginatedProducts, error)); ok {
		return rf(page, limit, search, category)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) *domain.PaginatedProducts); ok {
		r0 = rf(page, limit, search, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedProducts)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) error); ok {
		r1 = rf(page, limit, search, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByBarcode provides a mock function with given fields: barcode
func (_m *ProductRepository) GetByBarcode(barcode string) (*domain.Product, error) {
	ret := _m.Called(barcode)

	if len(ret) == 0 {
		panic("no return value specified for GetByBarcode")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Product, error)); ok {
		return rf(barcode)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Product); ok {
		r0 = rf(barcode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(barcode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ProductRepository) GetByID(id string) (*domain.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategories provides a mock function with no fields
func (_m *ProductRepository) GetCategories() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCategories")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLowStock provides a mock function with given fields: threshold
func (_m *ProductRepository) GetLowStock(threshold int) ([]domain.Product, error) {
	ret := _m.Called(threshold)

	if len(ret) == 0 {
		panic("no return value specified for GetLowStock")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Product, error)); ok {
		return rf(threshold)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Product); ok {
		r0 = rf(threshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(threshold)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStats provides a mock function with no fields
func (_m *ProductRepository) GetStats() (*domain.ProductStats, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.ProductStats
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.ProductStats, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.ProductStats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductStats)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: query, limit
func (_m *ProductRepository) Search(query string, limit int) ([]domain.Product, error) {
	ret := _m.Called(query, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]domain.Product, error)); ok {
		return rf(query, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []domain.Product); ok {
		r0 = rf(query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: product
func (_m *ProductRepository) Update(product *domain.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
