// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PurchaseOrderRepository is an autogenerated mock type for the PurchaseOrderRepository type
type PurchaseOrderRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: order
func (_m *PurchaseOrderRepository) Create(order *domain.PurchaseOrder) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.PurchaseOrder) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWithStockUpdate provides a mock function with given fields: order
func (_m *PurchaseOrderRepository) CreateWithStockUpdate(order *domain.PurchaseOrder) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithStockUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.PurchaseOrder) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *PurchaseOrderRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit, status
func (_m *PurchaseOrderRepository) GetAll(page int, limit int, status string) ([]domain.PurchaseOrder, int64, error) {
	ret := _m.Called(page, limit, status)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.PurchaseOrder
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.PurchaseOrder, int64, error)); ok {
		return rf(page, limit, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.PurchaseOrder); ok {
		r0 = rf(page, limit, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *PurchaseOrderRepository) GetByID(id string) (*domain.PurchaseOrder, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.PurchaseOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.PurchaseOrder, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.PurchaseOrder); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PurchaseOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceiveWithStockUpdate provides a mock function with given fields: id
func (_m *PurchaseOrderRepository) ReceiveWithStockUpdate(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveWithStockUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: order
func (_m *PurchaseOrderRepository) Update(order *domain.PurchaseOrder) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.PurchaseOrder) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: id, status
func (_m *PurchaseOrderRepository) UpdateStatus(id string, status string) error {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPurchaseOrderRepository creates a new instance of PurchaseOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPurchaseOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PurchaseOrderRepository {
	mock := &PurchaseOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
