// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RecurringInvoiceRepository is an autogenerated mock type for the RecurringInvoiceRepository type
type RecurringInvoiceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: invoice
func (_m *RecurringInvoiceRepository) Create(invoice *domain.RecurringInvoice) error {
	ret := _m.Called(invoice)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.RecurringInvoice) error); ok {
		r0 = rf(invoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *RecurringInvoiceRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit, status
func (_m *RecurringInvoiceRepository) GetAll(page int, limit int, status string) ([]domain.RecurringInvoice, int64, error) {
	ret := _m.Called(page, limit, status)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.RecurringInvoice
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.RecurringInvoice, int64, error)); ok {
		return rf(page, limit, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.RecurringInvoice); ok {
		r0 = rf(page, limit, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RecurringInvoice)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *RecurringInvoiceRepository) GetByID(id string) (*domain.RecurringInvoice, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.RecurringInvoice
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.RecurringInvoice, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.RecurringInvoice); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RecurringInvoice)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDueInvoices provides a mock function with no fields
func (_m *RecurringInvoiceRepository) GetDueInvoices() ([]domain.RecurringInvoice, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDueInvoices")
	}

	var r0 []domain.RecurringInvoice
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.RecurringInvoice, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.RecurringInvoice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RecurringInvoice)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkRun provides a mock function with given fields: id, saleID
func (_m *RecurringInvoiceRepository) MarkRun(id string, saleID string) error {
	ret := _m.Called(id, saleID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, saleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: invoice
func (_m *RecurringInvoiceRepository) Update(invoice *domain.RecurringInvoice) error {
	ret := _m.Called(invoice)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.RecurringInvoice) error); ok {
		r0 = rf(invoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecurringInvoiceRepository creates a new instance of RecurringInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecurringInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecurringInvoiceRepository {
	mock := &RecurringInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
