// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReorderRepository is an autogenerated mock type for the ReorderRepository type
type ReorderRepository struct {
	mock.Mock
}

// CreateRule provides a mock function with given fields: rule
func (_m *ReorderRepository) CreateRule(rule *domain.ReorderRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ReorderRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRule provides a mock function with given fields: id
func (_m *ReorderRepository) DeleteRule(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAlerts provides a mock function with no fields
func (_m *ReorderRepository) GetAlerts() ([]domain.ReorderAlert, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAlerts")
	}

	var r0 []domain.ReorderAlert
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ReorderAlert, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ReorderAlert); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReorderAlert)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRuleByID provides a mock function with given fields: id
func (_m *ReorderRepository) GetRuleByID(id string) (*domain.ReorderRule, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRuleByID")
	}

	var r0 *domain.ReorderRule
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.ReorderRule, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.ReorderRule); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReorderRule)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRuleByProductID provides a mock function with given fields: productID
func (_m *ReorderRepository) GetRuleByProductID(productID string) (*domain.ReorderRule, error) {
	ret := _m.Called(productID)

	if len(ret) == 0 {
		panic("no return value specified for GetRuleByProductID")
	}

	var r0 *domain.ReorderRule
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.ReorderRule, error)); ok {
		return rf(productID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.ReorderRule); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReorderRule)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRules provides a mock function with no fields
func (_m *ReorderRepository) GetRules() ([]domain.ReorderRule, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRules")
	}

	var r0 []domain.ReorderRule
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ReorderRule, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ReorderRule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReorderRule)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRule provides a mock function with given fields: rule
func (_m *ReorderRepository) UpdateRule(rule *domain.ReorderRule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ReorderRule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReorderRepository creates a new instance of ReorderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReorderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReorderRepository {
	mock := &ReorderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
