// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReportBuilderRepository is an autogenerated mock type for the ReportBuilderRepository type
type ReportBuilderRepository struct {
	mock.Mock
}

// CreateScheduledExport provides a mock function with given fields: e
func (_m *ReportBuilderRepository) CreateScheduledExport(e *domain.ScheduledExport) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for CreateScheduledExport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ScheduledExport) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTemplate provides a mock function with given fields: t
func (_m *ReportBuilderRepository) CreateTemplate(t *domain.ReportTemplate) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ReportTemplate) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteScheduledExport provides a mock function with given fields: id
func (_m *ReportBuilderRepository) DeleteScheduledExport(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScheduledExport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTemplate provides a mock function with given fields: id
func (_m *ReportBuilderRepository) DeleteTemplate(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDueExports provides a mock function with no fields
func (_m *ReportBuilderRepository) GetDueExports() ([]domain.ScheduledExport, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDueExports")
	}

	var r0 []domain.ScheduledExport
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ScheduledExport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ScheduledExport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ScheduledExport)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetScheduledExports provides a mock function with no fields
func (_m *ReportBuilderRepository) GetScheduledExports() ([]domain.ScheduledExport, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetScheduledExports")
	}

	var r0 []domain.ScheduledExport
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ScheduledExport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ScheduledExport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ScheduledExport)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplateByID provides a mock function with given fields: id
func (_m *ReportBuilderRepository) GetTemplateByID(id string) (*domain.ReportTemplate, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByID")
	}

	var r0 *domain.ReportTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.ReportTemplate, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.ReportTemplate); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ReportTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplates provides a mock function with no fields
func (_m *ReportBuilderRepository) GetTemplates() ([]domain.ReportTemplate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTemplates")
	}

	var r0 []domain.ReportTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ReportTemplate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ReportTemplate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReportTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateScheduledExport provides a mock function with given fields: e
func (_m *ReportBuilderRepository) UpdateScheduledExport(e *domain.ScheduledExport) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScheduledExport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ScheduledExport) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTemplate provides a mock function with given fields: t
func (_m *ReportBuilderRepository) UpdateTemplate(t *domain.ReportTemplate) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ReportTemplate) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReportBuilderRepository creates a new instance of ReportBuilderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportBuilderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportBuilderRepository {
	mock := &ReportBuilderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
