// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "bard/internal/repository"
)

// SaleRepository is an autogenerated mock type for the SaleRepository type
type SaleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: sale
func (_m *SaleRepository) Create(sale *domain.Sale) error {
	ret := _m.Called(sale)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Sale) error); ok {
		r0 = rf(sale)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateParkedSale provides a mock function with given fields: parked
func (_m *SaleRepository) CreateParkedSale(parked *domain.ParkedSale) error {
	ret := _m.Called(parked)

	if len(ret) == 0 {
		panic("no return value specified for CreateParkedSale")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ParkedSale) error); ok {
		r0 = rf(parked)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSaleWithStockUpdate provides a mock function with given fields: sale
func (_m *SaleRepository) CreateSaleWithStockUpdate(sale *domain.Sale) error {
	ret := _m.Called(sale)

	if len(ret) == 0 {
		panic("no return value specified for CreateSaleWithStockUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Sale) error); ok {
		r0 = rf(sale)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteParkedSale provides a mock function with given fields: id
func (_m *SaleRepository) DeleteParkedSale(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParkedSale")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit, search, status
func (_m *SaleRepository) GetAll(page int, limit int, search string, status string) (*domain.PaginatedSales, error) {
	ret := _m.Called(page, limit, search, status)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *domain.PaginatedSales
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) (*domain.PaginatedSales, error)); ok {
		return rf(page, limit, search, status)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) *domain.PaginatedSales); ok {
		r0 = rf(page, limit, search, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedSales)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) error); ok {
		r1 = rf(page, limit, search, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCustomerID provides a mock function with given fields: customerID, page, limit
func (_m *SaleRepository) GetByCustomerID(customerID string, page int, limit int) (*domain.PaginatedSales, error) {
	ret := _m.Called(customerID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByCustomerID")
	}

	var r0 *domain.PaginatedSales
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (*domain.PaginatedSales, error)); ok {
		return rf(customerID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *domain.PaginatedSales); ok {
		r0 = rf(customerID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedSales)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(customerID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByDateRange provides a mock function with given fields: startDate, endDate
func (_m *SaleRepository) GetByDateRange(startDate string, endDate string) ([]domain.Sale, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetByDateRange")
	}

	var r0 []domain.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]domain.Sale, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string) []domain.Sale); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *SaleRepository) GetByID(id string) (*domain.Sale, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Sale, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Sale); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParkedSales provides a mock function with no fields
func (_m *SaleRepository) GetParkedSales() ([]domain.ParkedSale, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetParkedSales")
	}

	var r0 []domain.ParkedSale
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.ParkedSale, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.ParkedSale); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ParkedSale)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecent provides a mock function with given fields: limit
func (_m *SaleRepository) GetRecent(limit int) ([]domain.Sale, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []domain.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Sale, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Sale); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStats provides a mock function with given fields: startDate, endDate
func (_m *SaleRepository) GetStats(startDate string, endDate string) (*domain.InvoiceStats, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.InvoiceStats
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.InvoiceStats, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.InvoiceStats); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InvoiceStats)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopProducts provides a mock function with given fields: limit, startDate, endDate
func (_m *SaleRepository) GetTopProducts(limit int, startDate string, endDate string) ([]domain.TopProduct, error) {
	ret := _m.Called(limit, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTopProducts")
	}

	var r0 []domain.TopProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string, string) ([]domain.TopProduct, error)); ok {
		return rf(limit, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(int, string, string) []domain.TopProduct); ok {
		r0 = rf(limit, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TopProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = rf(limit, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessPartialReturnWithStockUpdate provides a mock function with given fields: originalSaleID, returnItems
func (_m *SaleRepository) ProcessPartialReturnWithStockUpdate(originalSaleID string, returnItems []repository.PartialReturnItem) (*domain.Sale, error) {
	ret := _m.Called(originalSaleID, returnItems)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPartialReturnWithStockUpdate")
	}

	var r0 *domain.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []repository.PartialReturnItem) (*domain.Sale, error)); ok {
		return rf(originalSaleID, returnItems)
	}
	if rf, ok := ret.Get(0).(func(string, []repository.PartialReturnItem) *domain.Sale); ok {
		r0 = rf(originalSaleID, returnItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []repository.PartialReturnItem) error); ok {
		r1 = rf(originalSaleID, returnItems)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessReturnWithStockUpdate provides a mock function with given fields: originalSaleID
func (_m *SaleRepository) ProcessReturnWithStockUpdate(originalSaleID string) (*domain.Sale, error) {
	ret := _m.Called(originalSaleID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessReturnWithStockUpdate")
	}

	var r0 *domain.Sale
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Sale, error)); ok {
		return rf(originalSaleID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Sale); ok {
		r0 = rf(originalSaleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sale)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(originalSaleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: sale
func (_m *SaleRepository) Update(sale *domain.Sale) error {
	ret := _m.Called(sale)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Sale) error); ok {
		r0 = rf(sale)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSaleRepository creates a new instance of SaleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaleRepository {
	mock := &SaleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
