// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SegmentRepository is an autogenerated mock type for the SegmentRepository type
type SegmentRepository struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: member
func (_m *SegmentRepository) AddMember(member *domain.CustomerSegmentMember) error {
	ret := _m.Called(member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CustomerSegmentMember) error); ok {
		r0 = rf(member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCampaign provides a mock function with given fields: c
func (_m *SegmentRepository) CreateCampaign(c *domain.Campaign) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateCampaign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Campaign) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSegment provides a mock function with given fields: seg
func (_m *SegmentRepository) CreateSegment(seg *domain.CustomerSegment) error {
	ret := _m.Called(seg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSegment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CustomerSegment) error); ok {
		r0 = rf(seg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCampaign provides a mock function with given fields: id
func (_m *SegmentRepository) DeleteCampaign(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCampaign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSegment provides a mock function with given fields: id
func (_m *SegmentRepository) DeleteSegment(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSegment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCampaignByID provides a mock function with given fields: id
func (_m *SegmentRepository) GetCampaignByID(id string) (*domain.Campaign, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignByID")
	}

	var r0 *domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Campaign, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Campaign); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaigns provides a mock function with no fields
func (_m *SegmentRepository) GetCampaigns() ([]domain.Campaign, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCampaigns")
	}

	var r0 []domain.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Campaign, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Campaign); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSegmentByID provides a mock function with given fields: id
func (_m *SegmentRepository) GetSegmentByID(id string) (*domain.CustomerSegment, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSegmentByID")
	}

	var r0 *domain.CustomerSegment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.CustomerSegment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.CustomerSegment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CustomerSegment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSegmentMembers provides a mock function with given fields: segmentID
func (_m *SegmentRepository) GetSegmentMembers(segmentID string) ([]domain.CustomerSegmentMember, error) {
	ret := _m.Called(segmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetSegmentMembers")
	}

	var r0 []domain.CustomerSegmentMember
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.CustomerSegmentMember, error)); ok {
		return rf(segmentID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.CustomerSegmentMember); ok {
		r0 = rf(segmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CustomerSegmentMember)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(segmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSegments provides a mock function with no fields
func (_m *SegmentRepository) GetSegments() ([]domain.CustomerSegment, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSegments")
	}

	var r0 []domain.CustomerSegment
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.CustomerSegment, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.CustomerSegment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CustomerSegment)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: segmentID, customerID
func (_m *SegmentRepository) RemoveMember(segmentID string, customerID string) error {
	ret := _m.Called(segmentID, customerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(segmentID, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCampaign provides a mock function with given fields: c
func (_m *SegmentRepository) UpdateCampaign(c *domain.Campaign) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCampaign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Campaign) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSegment provides a mock function with given fields: seg
func (_m *SegmentRepository) UpdateSegment(seg *domain.CustomerSegment) error {
	ret := _m.Called(seg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSegment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CustomerSegment) error); ok {
		r0 = rf(seg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSegmentRepository creates a new instance of SegmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSegmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SegmentRepository {
	mock := &SegmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
