// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// CleanExpiredSessions provides a mock function with no fields
func (_m *SessionRepository) CleanExpiredSessions() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanExpiredSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSession provides a mock function with given fields: session
func (_m *SessionRepository) CreateSession(session *domain.Session) error {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Session) error); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSession provides a mock function with given fields: id
func (_m *SessionRepository) DeleteSession(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSessionByTokenHash provides a mock function with given fields: tokenHash
func (_m *SessionRepository) DeleteSessionByTokenHash(tokenHash string) error {
	ret := _m.Called(tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionByTokenHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSessionByTokenHash provides a mock function with given fields: tokenHash
func (_m *SessionRepository) GetSessionByTokenHash(tokenHash string) (*domain.Session, error) {
	ret := _m.Called(tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByTokenHash")
	}

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Session, error)); ok {
		return rf(tokenHash)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Session); ok {
		r0 = rf(tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastActive provides a mock function with given fields: id, activeTime
func (_m *SessionRepository) UpdateLastActive(id string, activeTime time.Time) error {
	ret := _m.Called(id, activeTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Time) error); ok {
		r0 = rf(id, activeTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
