// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SettingsRepository is an autogenerated mock type for the SettingsRepository type
type SettingsRepository struct {
	mock.Mock
}

// ExportDatabase provides a mock function with no fields
func (_m *SettingsRepository) ExportDatabase() (*domain.DatabaseExport, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExportDatabase")
	}

	var r0 *domain.DatabaseExport
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.DatabaseExport, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.DatabaseExport); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DatabaseExport)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferences provides a mock function with no fields
func (_m *SettingsRepository) GetPreferences() (*domain.AppPreferences, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPreferences")
	}

	var r0 *domain.AppPreferences
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.AppPreferences, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.AppPreferences); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppPreferences)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImportDatabase provides a mock function with given fields: data
func (_m *SettingsRepository) ImportDatabase(data *domain.DatabaseExport) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ImportDatabase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.DatabaseExport) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetDatabase provides a mock function with no fields
func (_m *SettingsRepository) ResetDatabase() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResetDatabase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePreferences provides a mock function with given fields: prefs
func (_m *SettingsRepository) UpdatePreferences(prefs *domain.AppPreferences) error {
	ret := _m.Called(prefs)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.AppPreferences) error); ok {
		r0 = rf(prefs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSettingsRepository creates a new instance of SettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsRepository {
	mock := &SettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
