// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ShiftRepository is an autogenerated mock type for the ShiftRepository type
type ShiftRepository struct {
	mock.Mock
}

// AddCashMovement provides a mock function with given fields: movement
func (_m *ShiftRepository) AddCashMovement(movement *domain.CashMovement) error {
	ret := _m.Called(movement)

	if len(ret) == 0 {
		panic("no return value specified for AddCashMovement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CashMovement) error); ok {
		r0 = rf(movement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields: shift
func (_m *ShiftRepository) Close(shift *domain.Shift) error {
	ret := _m.Called(shift)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Shift) error); ok {
		r0 = rf(shift)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: shift
func (_m *ShiftRepository) Create(shift *domain.Shift) error {
	ret := _m.Called(shift)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Shift) error); ok {
		r0 = rf(shift)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActive provides a mock function with given fields: staffID
func (_m *ShiftRepository) GetActive(staffID string) (*domain.Shift, error) {
	ret := _m.Called(staffID)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 *domain.Shift
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Shift, error)); ok {
		return rf(staffID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Shift); ok {
		r0 = rf(staffID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shift)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(staffID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: page, limit
func (_m *ShiftRepository) GetAll(page int, limit int) ([]domain.Shift, int64, error) {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Shift
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.Shift, int64, error)); ok {
		return rf(page, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.Shift); ok {
		r0 = rf(page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Shift)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCashMovements provides a mock function with given fields: shiftID
func (_m *ShiftRepository) GetCashMovements(shiftID string) ([]domain.CashMovement, error) {
	ret := _m.Called(shiftID)

	if len(ret) == 0 {
		panic("no return value specified for GetCashMovements")
	}

	var r0 []domain.CashMovement
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.CashMovement, error)); ok {
		return rf(shiftID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.CashMovement); ok {
		r0 = rf(shiftID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CashMovement)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shiftID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShiftRepository creates a new instance of ShiftRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShiftRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShiftRepository {
	mock := &ShiftRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
