// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// StaffRepository is an autogenerated mock type for the StaffRepository type
type StaffRepository struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: username, password
func (_m *StaffRepository) Authenticate(username string, password string) (*domain.Staff, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.Staff, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.Staff); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: staff
func (_m *StaffRepository) Create(staff *domain.Staff) error {
	ret := _m.Called(staff)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Staff) error); ok {
		r0 = rf(staff)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *StaffRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *StaffRepository) GetAll() ([]domain.Staff, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Staff, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Staff); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *StaffRepository) GetByID(id string) (*domain.Staff, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Staff, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Staff); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUsername provides a mock function with given fields: username
func (_m *StaffRepository) GetByUsername(username string) (*domain.Staff, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *domain.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Staff, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Staff); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: staff
func (_m *StaffRepository) Update(staff *domain.Staff) error {
	ret := _m.Called(staff)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Staff) error); ok {
		r0 = rf(staff)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateFields provides a mock function with given fields: id, fields
func (_m *StaffRepository) UpdateFields(id string, fields map[string]interface{}) error {
	ret := _m.Called(id, fields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFields")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(id, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePassword provides a mock function with given fields: id, hashedPassword
func (_m *StaffRepository) UpdatePassword(id string, hashedPassword string) error {
	ret := _m.Called(id, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStaffRepository creates a new instance of StaffRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStaffRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StaffRepository {
	mock := &StaffRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
