// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// StatsRepository is an autogenerated mock type for the StatsRepository type
type StatsRepository struct {
	mock.Mock
}

// GetDashboardStats provides a mock function with no fields
func (_m *StatsRepository) GetDashboardStats() (*domain.DashboardStats, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardStats")
	}

	var r0 *domain.DashboardStats
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.DashboardStats, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.DashboardStats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DashboardStats)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStatsRepository creates a new instance of StatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsRepository {
	mock := &StatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
