// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// StockAdjustmentRepository is an autogenerated mock type for the StockAdjustmentRepository type
type StockAdjustmentRepository struct {
	mock.Mock
}

// CreateAdjustment provides a mock function with given fields: adj
func (_m *StockAdjustmentRepository) CreateAdjustment(adj *domain.StockAdjustment) error {
	ret := _m.Called(adj)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdjustment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.StockAdjustment) error); ok {
		r0 = rf(adj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAdjustmentWithStockUpdate provides a mock function with given fields: adj, product
func (_m *StockAdjustmentRepository) CreateAdjustmentWithStockUpdate(adj *domain.StockAdjustment, product *domain.Product) error {
	ret := _m.Called(adj, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdjustmentWithStockUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.StockAdjustment, *domain.Product) error); ok {
		r0 = rf(adj, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWasteRecord provides a mock function with given fields: record
func (_m *StockAdjustmentRepository) CreateWasteRecord(record *domain.WasteRecord) error {
	ret := _m.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for CreateWasteRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.WasteRecord) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWasteRecordWithStockUpdate provides a mock function with given fields: record, product
func (_m *StockAdjustmentRepository) CreateWasteRecordWithStockUpdate(record *domain.WasteRecord, product *domain.Product) error {
	ret := _m.Called(record, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateWasteRecordWithStockUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.WasteRecord, *domain.Product) error); ok {
		r0 = rf(record, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAdjustments provides a mock function with given fields: page, limit, adjType
func (_m *StockAdjustmentRepository) GetAdjustments(page int, limit int, adjType string) ([]domain.StockAdjustment, int64, error) {
	ret := _m.Called(page, limit, adjType)

	if len(ret) == 0 {
		panic("no return value specified for GetAdjustments")
	}

	var r0 []domain.StockAdjustment
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.StockAdjustment, int64, error)); ok {
		return rf(page, limit, adjType)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.StockAdjustment); ok {
		r0 = rf(page, limit, adjType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StockAdjustment)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, adjType)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, adjType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetWasteRecords provides a mock function with given fields: page, limit, wasteType
func (_m *StockAdjustmentRepository) GetWasteRecords(page int, limit int, wasteType string) ([]domain.WasteRecord, int64, error) {
	ret := _m.Called(page, limit, wasteType)

	if len(ret) == 0 {
		panic("no return value specified for GetWasteRecords")
	}

	var r0 []domain.WasteRecord
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]domain.WasteRecord, int64, error)); ok {
		return rf(page, limit, wasteType)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []domain.WasteRecord); ok {
		r0 = rf(page, limit, wasteType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WasteRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, limit, wasteType)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, limit, wasteType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetWasteSummary provides a mock function with given fields: startDate, endDate
func (_m *StockAdjustmentRepository) GetWasteSummary(startDate string, endDate string) ([]domain.WasteRecord, error) {
	ret := _m.Called(startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetWasteSummary")
	}

	var r0 []domain.WasteRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]domain.WasteRecord, error)); ok {
		return rf(startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string) []domain.WasteRecord); ok {
		r0 = rf(startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WasteRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStockAdjustmentRepository creates a new instance of StockAdjustmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockAdjustmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockAdjustmentRepository {
	mock := &StockAdjustmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
