// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SupplierRepository is an autogenerated mock type for the SupplierRepository type
type SupplierRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: supplier
func (_m *SupplierRepository) Create(supplier *domain.Supplier) error {
	ret := _m.Called(supplier)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Supplier) error); ok {
		r0 = rf(supplier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *SupplierRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *SupplierRepository) GetAll() ([]domain.Supplier, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Supplier, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Supplier); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *SupplierRepository) GetByID(id string) (*domain.Supplier, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Supplier
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Supplier, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Supplier); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Supplier)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: supplier
func (_m *SupplierRepository) Update(supplier *domain.Supplier) error {
	ret := _m.Called(supplier)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Supplier) error); ok {
		r0 = rf(supplier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSupplierRepository creates a new instance of SupplierRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupplierRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupplierRepository {
	mock := &SupplierRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
