// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TaxRepository is an autogenerated mock type for the TaxRepository type
type TaxRepository struct {
	mock.Mock
}

// CreateProductTax provides a mock function with given fields: pt
func (_m *TaxRepository) CreateProductTax(pt *domain.ProductTax) error {
	ret := _m.Called(pt)

	if len(ret) == 0 {
		panic("no return value specified for CreateProductTax")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ProductTax) error); ok {
		r0 = rf(pt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTaxRate provides a mock function with given fields: rate
func (_m *TaxRepository) CreateTaxRate(rate *domain.TaxRate) error {
	ret := _m.Called(rate)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaxRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.TaxRate) error); ok {
		r0 = rf(rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProductTax provides a mock function with given fields: productID, taxRateID
func (_m *TaxRepository) DeleteProductTax(productID string, taxRateID string) error {
	ret := _m.Called(productID, taxRateID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductTax")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(productID, taxRateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTaxRate provides a mock function with given fields: id
func (_m *TaxRepository) DeleteTaxRate(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaxRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDefaultTaxRate provides a mock function with no fields
func (_m *TaxRepository) GetDefaultTaxRate() (*domain.TaxRate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultTaxRate")
	}

	var r0 *domain.TaxRate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.TaxRate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.TaxRate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TaxRate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductTaxes provides a mock function with given fields: productID
func (_m *TaxRepository) GetProductTaxes(productID string) ([]domain.ProductTax, error) {
	ret := _m.Called(productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductTaxes")
	}

	var r0 []domain.ProductTax
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.ProductTax, error)); ok {
		return rf(productID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.ProductTax); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductTax)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaxRateByCode provides a mock function with given fields: code
func (_m *TaxRepository) GetTaxRateByCode(code string) (*domain.TaxRate, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetTaxRateByCode")
	}

	var r0 *domain.TaxRate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.TaxRate, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.TaxRate); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TaxRate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaxRateByID provides a mock function with given fields: id
func (_m *TaxRepository) GetTaxRateByID(id string) (*domain.TaxRate, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaxRateByID")
	}

	var r0 *domain.TaxRate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.TaxRate, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.TaxRate); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TaxRate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaxRates provides a mock function with no fields
func (_m *TaxRepository) GetTaxRates() ([]domain.TaxRate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTaxRates")
	}

	var r0 []domain.TaxRate
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.TaxRate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.TaxRate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TaxRate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaxRate provides a mock function with given fields: rate
func (_m *TaxRepository) UpdateTaxRate(rate *domain.TaxRate) error {
	ret := _m.Called(rate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaxRate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.TaxRate) error); ok {
		r0 = rf(rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaxRepository creates a new instance of TaxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaxRepository {
	mock := &TaxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
