// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "bard/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: wallet
func (_m *WalletRepository) Create(wallet *domain.CustomerWallet) error {
	ret := _m.Called(wallet)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CustomerWallet) error); ok {
		r0 = rf(wallet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTransaction provides a mock function with given fields: tx
func (_m *WalletRepository) CreateTransaction(tx *domain.WalletTransaction) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.WalletTransaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCustomerID provides a mock function with given fields: customerID
func (_m *WalletRepository) GetByCustomerID(customerID string) (*domain.CustomerWallet, error) {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCustomerID")
	}

	var r0 *domain.CustomerWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.CustomerWallet, error)); ok {
		return rf(customerID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.CustomerWallet); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CustomerWallet)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactions provides a mock function with given fields: customerID, page, limit
func (_m *WalletRepository) GetTransactions(customerID string, page int, limit int) ([]domain.WalletTransaction, int64, error) {
	ret := _m.Called(customerID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []domain.WalletTransaction
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]domain.WalletTransaction, int64, error)); ok {
		return rf(customerID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []domain.WalletTransaction); ok {
		r0 = rf(customerID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) int64); ok {
		r1 = rf(customerID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = rf(customerID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: wallet
func (_m *WalletRepository) Update(wallet *domain.CustomerWallet) error {
	ret := _m.Called(wallet)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.CustomerWallet) error); ok {
		r0 = rf(wallet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
