// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"bard/internal/audit"
	"bard/internal/cache"
	"bard/internal/crypto"
	"bard/internal/handler"
	"bard/internal/logger"
	"bard/internal/middleware"
	"bard/internal/repository"
	"bard/internal/repository/sqlite"
	"bard/internal/service"
	"github.com/google/wire"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// InitializeApp builds and returns a fully wired handler.App.
// Wire will generate the actual implementation in wire_gen.go.
func InitializeApp(db *gorm.DB) (*handler.App, func(), error) {
	productRepository := sqlite.NewProductRepository(db)
	productCache := ProvideProductCache()
	logger := ProvideLogger()
	productService := service.NewProductService(productRepository, productCache, logger)
	saleRepository := sqlite.NewSaleRepository(db)
	customerRepository := sqlite.NewCustomerRepository(db)
	saleCache := ProvideSaleCache()
	saleService := service.NewSaleService(saleRepository, productRepository, customerRepository, saleCache, logger)
	customerCache := ProvideCustomerCache()
	customerService := service.NewCustomerService(customerRepository, customerCache, logger)
	staffRepository := sqlite.NewStaffRepository(db)
	staffService := service.NewStaffService(staffRepository, logger)
	financeRepository := sqlite.NewFinanceRepository(db)
	financeService := service.NewFinanceService(financeRepository, logger)
	settingsRepository := sqlite.NewSettingsRepository(db)
	encryptor := ProvideEncryptor()
	settingsService := service.NewSettingsService(settingsRepository, encryptor, logger)
	statsRepository := sqlite.NewStatsRepository(db)
	dashboardCache := ProvideDashboardCache()
	statsService := service.NewStatsService(statsRepository, dashboardCache, logger)
	shiftRepository := sqlite.NewShiftRepository(db)
	shiftService := service.NewShiftService(shiftRepository, logger)
	supplierRepository := sqlite.NewSupplierRepository(db)
	supplierService := service.NewSupplierService(supplierRepository, logger)
	purchaseOrderRepository := sqlite.NewPurchaseOrderRepository(db)
	purchaseOrderService := service.NewPurchaseOrderService(purchaseOrderRepository, productRepository, logger)
	rateLimiter := ProvideRateLimiter()
	sessionRepository := sqlite.NewSessionRepository(db)
	authMiddleware := ProvideAuthMiddleware(logger, rateLimiter, sessionRepository, staffRepository)
	repository := sqlite.NewAuditRepository(db)
	auditService := audit.NewAuditService(repository, logger)
	loyaltyRepository := sqlite.NewLoyaltyRepository(db)
	loyaltyService := service.NewLoyaltyService(loyaltyRepository, customerRepository, logger)
	notificationRepository := sqlite.NewNotificationRepository(db)
	notificationService := service.NewNotificationService(notificationRepository, logger)
	branchRepository := sqlite.NewBranchRepository(db)
	branchService := service.NewBranchService(branchRepository, logger)
	kitRepository := sqlite.NewKitRepository(db)
	kitService := service.NewKitService(kitRepository, logger)
	recurringInvoiceRepository := sqlite.NewRecurringInvoiceRepository(db)
	recurringInvoiceService := service.NewRecurringInvoiceService(recurringInvoiceRepository, logger)
	analyticsService := service.NewAnalyticsService(saleRepository, productRepository, customerRepository, logger)
	giftCardRepository := sqlite.NewGiftCardRepository(db)
	giftCardService := service.NewGiftCardService(giftCardRepository, logger)
	kitchenRepository := sqlite.NewKitchenRepository(db)
	kitchenService := service.NewKitchenService(kitchenRepository, logger)
	walletRepository := sqlite.NewWalletRepository(db)
	walletService := service.NewWalletService(walletRepository, logger)
	stockAdjustmentRepository := sqlite.NewStockAdjustmentRepository(db)
	stockAdjustmentService := service.NewStockAdjustmentService(stockAdjustmentRepository, productRepository, logger)
	currencyRepository := sqlite.NewCurrencyRepository(db)
	currencyService := service.NewCurrencyService(currencyRepository, logger)
	messagingRepository := sqlite.NewMessagingRepository(db)
	messagingService := service.NewMessagingService(messagingRepository, logger)
	commissionRepository := sqlite.NewCommissionRepository(db)
	commissionService := service.NewCommissionService(commissionRepository, saleRepository, logger)
	segmentRepository := sqlite.NewSegmentRepository(db)
	campaignService := service.NewCampaignService(segmentRepository, customerRepository, logger)
	taxRepository := sqlite.NewTaxRepository(db)
	taxService := service.NewTaxService(taxRepository, logger)
	kioskRepository := sqlite.NewKioskRepository(db)
	kioskService := service.NewKioskService(kioskRepository, logger)
	deliveryRepository := sqlite.NewDeliveryRepository(db)
	deliveryService := service.NewDeliveryService(deliveryRepository, logger)
	reorderRepository := sqlite.NewReorderRepository(db)
	reorderService := service.NewReorderService(reorderRepository, productRepository, logger)
	budgetRepository := sqlite.NewBudgetRepository(db)
	budgetService := service.NewBudgetService(budgetRepository, logger)
	reportBuilderRepository := sqlite.NewReportBuilderRepository(db)
	reportBuilderService := service.NewReportBuilderService(reportBuilderRepository, logger)
	app := handler.NewApp(productService, saleService, customerService, staffService, financeService, settingsService, statsService, shiftService, supplierService, purchaseOrderService, authMiddleware, rateLimiter, auditService, logger, loyaltyService, notificationService, branchService, kitService, recurringInvoiceService, analyticsService, giftCardService, kitchenService, walletService, stockAdjustmentService, currencyService, messagingService, commissionService, campaignService, taxService, kioskService, deliveryService, reorderService, budgetService, reportBuilderService)
	return app, func() {
	}, nil
}

// wire.go:

// ProvideLogger creates a new application logger.
func ProvideLogger() *logger.Logger {
	return logger.New(logger.LevelInfo, true)
}

// ProvideCaches creates all cache instances.
func ProvideDashboardCache() *cache.DashboardCache { return cache.NewDashboardCache() }

func ProvideProductCache() *cache.ProductCache { return cache.NewProductCache() }

func ProvideSaleCache() *cache.SaleCache { return cache.NewSaleCache() }

func ProvideCustomerCache() *cache.CustomerCache { return cache.NewCustomerCache() }

// ProvideRateLimiter creates the rate limiter middleware.
func ProvideRateLimiter() *middleware.RateLimiter {
	return middleware.NewRateLimiter(5, 15*time.Minute, 30*time.Minute)
}

// ProvideAuthMiddleware creates the authentication middleware.
func ProvideAuthMiddleware(log *logger.Logger, rl *middleware.RateLimiter, sessionRepo repository.SessionRepository, staffRepo repository.StaffRepository) *middleware.AuthMiddleware {
	return middleware.NewAuthMiddleware(log, rl, sessionRepo, staffRepo)
}

// ProvideEncryptor creates the encryption service.
func ProvideEncryptor() *crypto.Encryptor {
	km, err := crypto.NewKeyManager()
	if err != nil {
		return &crypto.Encryptor{}
	}
	key, err := km.GetOrCreateKey()
	if err != nil {
		return &crypto.Encryptor{}
	}
	enc, err := crypto.NewEncryptor(key)
	if err != nil {
		return &crypto.Encryptor{}
	}
	crypto.GlobalEncryptor = enc
	return enc
}

// InfrastructureSet groups infrastructure providers (logging, caching, middleware).
var InfrastructureSet = wire.NewSet(
	ProvideLogger,
	ProvideDashboardCache,
	ProvideProductCache,
	ProvideSaleCache,
	ProvideCustomerCache,
	ProvideRateLimiter,
	ProvideAuthMiddleware,
	ProvideEncryptor,
)

// RepositorySet groups all repository providers.
var RepositorySet = wire.NewSet(sqlite.NewProductRepository, sqlite.NewSaleRepository, sqlite.NewCustomerRepository, sqlite.NewStaffRepository, sqlite.NewFinanceRepository, sqlite.NewSettingsRepository, sqlite.NewStatsRepository, sqlite.NewShiftRepository, sqlite.NewSupplierRepository, sqlite.NewPurchaseOrderRepository, sqlite.NewLoyaltyRepository, sqlite.NewNotificationRepository, sqlite.NewBranchRepository, sqlite.NewKitRepository, sqlite.NewRecurringInvoiceRepository, sqlite.NewGiftCardRepository, sqlite.NewKitchenRepository, sqlite.NewWalletRepository, sqlite.NewStockAdjustmentRepository, sqlite.NewCurrencyRepository, sqlite.NewMessagingRepository, sqlite.NewCommissionRepository, sqlite.NewSegmentRepository, sqlite.NewTaxRepository, sqlite.NewKioskRepository, sqlite.NewDeliveryRepository, sqlite.NewReorderRepository, sqlite.NewBudgetRepository, sqlite.NewReportBuilderRepository, sqlite.NewAuditRepository, sqlite.NewSessionRepository)

// ServiceSet groups all service providers.
var ServiceSet = wire.NewSet(service.NewProductService, service.NewSaleService, service.NewCustomerService, service.NewStaffService, service.NewFinanceService, service.NewSettingsService, service.NewStatsService, service.NewShiftService, service.NewSupplierService, service.NewPurchaseOrderService, service.NewLoyaltyService, service.NewNotificationService, service.NewBranchService, service.NewKitService, service.NewRecurringInvoiceService, service.NewAnalyticsService, service.NewGiftCardService, service.NewKitchenService, service.NewWalletService, service.NewStockAdjustmentService, service.NewCurrencyService, service.NewMessagingService, service.NewCommissionService, service.NewCampaignService, service.NewTaxService, service.NewKioskService, service.NewDeliveryService, service.NewReorderService, service.NewBudgetService, service.NewReportBuilderService, audit.NewAuditService)

// AppSet groups everything needed to build the handler.App.
var AppSet = wire.NewSet(
	InfrastructureSet,
	RepositorySet,
	ServiceSet, handler.NewApp,
)
