// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddCashMovement(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function CalculateInstallmentPlan(arg1:number,arg2:number,arg3:number):Promise<domain.InstallmentPlan>;

export function Close():Promise<void>;

export function CloseShift(arg1:string,arg2:number):Promise<domain.Shift>;

export function CreateCustomer(arg1:domain.Customer):Promise<void>;

export function CreateExpense(arg1:domain.Expense):Promise<void>;

export function CreatePayment(arg1:domain.Payment):Promise<void>;

export function CreateProduct(arg1:domain.Product):Promise<void>;

export function CreatePurchaseOrder(arg1:domain.PurchaseOrder):Promise<void>;

export function CreateSale(arg1:domain.Sale):Promise<void>;

export function CreateStaff(arg1:domain.Staff):Promise<void>;

export function CreateSupplier(arg1:domain.Supplier):Promise<void>;

export function DeleteCustomer(arg1:string):Promise<void>;

export function DeleteExpense(arg1:string):Promise<void>;

export function DeleteParkedSale(arg1:number):Promise<void>;

export function DeleteProduct(arg1:string):Promise<void>;

export function DeletePurchaseOrder(arg1:string):Promise<void>;

export function DeleteStaff(arg1:string):Promise<void>;

export function DeleteSupplier(arg1:string):Promise<void>;

export function ExportDatabase():Promise<domain.DatabaseExport>;

export function GetActiveShift(arg1:string):Promise<domain.Shift>;

export function GetCashMovements(arg1:string):Promise<Array<domain.CashMovement>>;

export function GetCategories():Promise<Array<string>>;

export function GetCustomer(arg1:string):Promise<domain.Customer>;

export function GetCustomers(arg1:number,arg2:number,arg3:string):Promise<Array<domain.Customer>>;

export function GetDashboardStats():Promise<domain.DashboardStats>;

export function GetExpenses(arg1:number,arg2:number,arg3:string):Promise<Array<domain.Expense>>;

export function GetParkedSales():Promise<Array<domain.ParkedSale>>;

export function GetPayments(arg1:string):Promise<Array<domain.Payment>>;

export function GetPreferences():Promise<domain.AppPreferences>;

export function GetProduct(arg1:string):Promise<domain.Product>;

export function GetProductByBarcode(arg1:string):Promise<domain.Product>;

export function GetProductStats():Promise<domain.ProductStats>;

export function GetProducts(arg1:number,arg2:number,arg3:string,arg4:string):Promise<domain.PaginatedProducts>;

export function GetPurchaseOrder(arg1:string):Promise<domain.PurchaseOrder>;

export function GetPurchaseOrders(arg1:number,arg2:number,arg3:string):Promise<domain.PaginatedResponse_bard_internal_domain_PurchaseOrder_>;

export function GetRecentSales(arg1:number):Promise<Array<domain.Sale>>;

export function GetSale(arg1:string):Promise<domain.Sale>;

export function GetSales(arg1:number,arg2:number,arg3:string,arg4:string):Promise<domain.PaginatedSales>;

export function GetShifts(arg1:number,arg2:number):Promise<Array<domain.Shift>>;

export function GetStaff():Promise<Array<domain.Staff>>;

export function GetSupplier(arg1:string):Promise<domain.Supplier>;

export function GetSuppliers():Promise<Array<domain.Supplier>>;

export function Greet(arg1:string):Promise<string>;

export function ImportDatabase(arg1:domain.DatabaseExport):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<domain.Staff>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function ParkSale(arg1:domain.ParkedSale):Promise<void>;

export function ProcessReturn(arg1:string):Promise<domain.Sale>;

export function ReceivePurchaseOrder(arg1:string):Promise<void>;

export function ResetDatabase():Promise<void>;

export function SearchCustomerByPhone(arg1:string):Promise<domain.Customer>;

export function SearchProducts(arg1:string,arg2:number):Promise<Array<domain.Product>>;

export function StartShift(arg1:string,arg2:string,arg3:number):Promise<domain.Shift>;

export function UpdateCustomer(arg1:domain.Customer):Promise<void>;

export function UpdateExpense(arg1:domain.Expense):Promise<void>;

export function UpdatePreferences(arg1:domain.AppPreferences):Promise<void>;

export function UpdateProduct(arg1:domain.Product):Promise<void>;

export function UpdatePurchaseOrder(arg1:domain.PurchaseOrder):Promise<void>;

export function UpdateStaff(arg1:domain.Staff):Promise<void>;

export function UpdateSupplier(arg1:domain.Supplier):Promise<void>;
