// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCashMovement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handler']['App']['AddCashMovement'](arg1, arg2, arg3, arg4, arg5);
}

export function CalculateInstallmentPlan(arg1, arg2, arg3) {
  return window['go']['handler']['App']['CalculateInstallmentPlan'](arg1, arg2, arg3);
}

export function CloseShift(arg1, arg2) {
  return window['go']['handler']['App']['CloseShift'](arg1, arg2);
}

export function CreateCustomer(arg1) {
  return window['go']['handler']['App']['CreateCustomer'](arg1);
}

export function CreateExpense(arg1) {
  return window['go']['handler']['App']['CreateExpense'](arg1);
}

export function CreatePayment(arg1) {
  return window['go']['handler']['App']['CreatePayment'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['handler']['App']['CreateProduct'](arg1);
}

export function CreatePurchaseOrder(arg1) {
  return window['go']['handler']['App']['CreatePurchaseOrder'](arg1);
}

export function CreateSale(arg1) {
  return window['go']['handler']['App']['CreateSale'](arg1);
}

export function CreateStaff(arg1) {
  return window['go']['handler']['App']['CreateStaff'](arg1);
}

export function CreateSupplier(arg1) {
  return window['go']['handler']['App']['CreateSupplier'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['handler']['App']['DeleteCustomer'](arg1);
}

export function DeleteExpense(arg1) {
  return window['go']['handler']['App']['DeleteExpense'](arg1);
}

export function DeleteParkedSale(arg1) {
  return window['go']['handler']['App']['DeleteParkedSale'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['handler']['App']['DeleteProduct'](arg1);
}

export function DeletePurchaseOrder(arg1) {
  return window['go']['handler']['App']['DeletePurchaseOrder'](arg1);
}

export function DeleteStaff(arg1) {
  return window['go']['handler']['App']['DeleteStaff'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['handler']['App']['DeleteSupplier'](arg1);
}

export function ExportDatabase() {
  return window['go']['handler']['App']['ExportDatabase']();
}

export function GetActiveShift(arg1) {
  return window['go']['handler']['App']['GetActiveShift'](arg1);
}

export function GetCashMovements(arg1) {
  return window['go']['handler']['App']['GetCashMovements'](arg1);
}

export function GetCategories() {
  return window['go']['handler']['App']['GetCategories']();
}

export function GetCustomer(arg1) {
  return window['go']['handler']['App']['GetCustomer'](arg1);
}

export function GetCustomers(arg1, arg2, arg3) {
  return window['go']['handler']['App']['GetCustomers'](arg1, arg2, arg3);
}

export function GetDashboardStats() {
  return window['go']['handler']['App']['GetDashboardStats']();
}

export function GetExpenses(arg1, arg2, arg3) {
  return window['go']['handler']['App']['GetExpenses'](arg1, arg2, arg3);
}

export function GetParkedSales() {
  return window['go']['handler']['App']['GetParkedSales']();
}

export function GetPayments(arg1) {
  return window['go']['handler']['App']['GetPayments'](arg1);
}

export function GetPreferences() {
  return window['go']['handler']['App']['GetPreferences']();
}

export function GetProduct(arg1) {
  return window['go']['handler']['App']['GetProduct'](arg1);
}

export function GetProductByBarcode(arg1) {
  return window['go']['handler']['App']['GetProductByBarcode'](arg1);
}

export function GetProductStats() {
  return window['go']['handler']['App']['GetProductStats']();
}

export function GetProducts(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['App']['GetProducts'](arg1, arg2, arg3, arg4);
}

export function GetPurchaseOrder(arg1) {
  return window['go']['handler']['App']['GetPurchaseOrder'](arg1);
}

export function GetPurchaseOrders(arg1, arg2, arg3) {
  return window['go']['handler']['App']['GetPurchaseOrders'](arg1, arg2, arg3);
}

export function GetRecentSales(arg1) {
  return window['go']['handler']['App']['GetRecentSales'](arg1);
}

export function GetSale(arg1) {
  return window['go']['handler']['App']['GetSale'](arg1);
}

export function GetSales(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['App']['GetSales'](arg1, arg2, arg3, arg4);
}

export function GetStaff() {
  return window['go']['handler']['App']['GetStaff']();
}

export function GetSupplier(arg1) {
  return window['go']['handler']['App']['GetSupplier'](arg1);
}

export function GetSuppliers() {
  return window['go']['handler']['App']['GetSuppliers']();
}

export function ImportDatabase(arg1) {
  return window['go']['handler']['App']['ImportDatabase'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['handler']['App']['Login'](arg1, arg2);
}

export function ParkSale(arg1) {
  return window['go']['handler']['App']['ParkSale'](arg1);
}

export function ProcessReturn(arg1) {
  return window['go']['handler']['App']['ProcessReturn'](arg1);
}

export function ReceivePurchaseOrder(arg1) {
  return window['go']['handler']['App']['ReceivePurchaseOrder'](arg1);
}

export function ResetDatabase() {
  return window['go']['handler']['App']['ResetDatabase']();
}

export function SearchCustomerByPhone(arg1) {
  return window['go']['handler']['App']['SearchCustomerByPhone'](arg1);
}

export function SearchProducts(arg1, arg2) {
  return window['go']['handler']['App']['SearchProducts'](arg1, arg2);
}

export function StartShift(arg1, arg2, arg3) {
  return window['go']['handler']['App']['StartShift'](arg1, arg2, arg3);
}

export function UpdateCustomer(arg1) {
  return window['go']['handler']['App']['UpdateCustomer'](arg1);
}

export function UpdateExpense(arg1) {
  return window['go']['handler']['App']['UpdateExpense'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['handler']['App']['UpdatePreferences'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['handler']['App']['UpdateProduct'](arg1);
}

export function UpdatePurchaseOrder(arg1) {
  return window['go']['handler']['App']['UpdatePurchaseOrder'](arg1);
}

export function UpdateStaff(arg1) {
  return window['go']['handler']['App']['UpdateStaff'](arg1);
}

export function UpdateSupplier(arg1) {
  return window['go']['handler']['App']['UpdateSupplier'](arg1);
}
